version: '2.21'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: "s3,lambda"
      DEBUG: "1"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"

volumes:
  mongodb_data:

networks:
  default:
    name: localstack_network
